### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by larsimbach-unibe** [embodied-computation-group/Cardioception#62]
Hi @LegrandNico,

There is an import error with the systole package: "ImportError: cannot import name 'oxi_peaks' from 'systole.detection'".

(using systole version 0.2.2, as 'findOximeter()' could not be found in systole 0.2.4 in recoring.py)

Best Regards
Lars

**Comment by LegrandNico** [comment]
Hi @larsimbach-unibe ,

Thank you for reporting this. Yes, this error has been around for some time now 😬, if you are using cardioception 0.4.3, you have to use systole 0.1.3 to make it work.

This has otherwise been fixed in #67 and should not be a problem anymore in the next release 0.4.4.

We now also provide an `environment.yml` file that can create a fully compatible conda environment out of the box, so installing the task should be easier.

Best regards,

**Comment by larsimbach-unibe** [comment]
Thank you for your answer @LegrandNico ! I noticed the gitter chat too late and saw some discussion about the same problem. For now it seems to work :-D .

Best regards
